<?php
if(!defined('T_PROVEIDOR')) define('T_PROVEIDOR','proveidor');
if(!defined('T_PROVEIDORS')) define('T_PROVEIDORS','proveidors');
if(!defined('T_PROVEIDOR_PREUS')) define('T_PROVEIDOR_PREUS','preus proveidor');
if(!defined('T_PROVEIDOR_DADES_FISCALS')) define('T_PROVEIDOR_DADES_FISCALS','dades fiscals proveidor');
if(!defined('T_PROVEIDOR_ERROR_ESBORRAR_COMANDA')) define('T_PROVEIDOR_ERROR_ESBORRAR_COMANDA','El proveidor no es pot eliminar, té comandes assignades');
if(!defined('T_PROVEIDOR_ERROR_ESBORRAR_ALBARA')) define('T_PROVEIDOR_ERROR_ESBORRAR_ALBARA','El proveidor no es pot eliminar, té albarans assignats');
if(!defined('T_PROVEIDOR_ERROR_ESBORRAR_FACTURA')) define('T_PROVEIDOR_ERROR_ESBORRAR_FACTURA','El proveidor no es pot eliminar, té factures assignades');
if(!defined('T_PROVEIDOR_DADES_FACTURACIO')) define('T_PROVEIDOR_DADES_FACTURACIO','dades facturació');
if(!defined('T_PROVEIDOR_COMPTE_COMPTABLE')) define('T_PROVEIDOR_COMPTE_COMPTABLE','compte comptable');
if(!defined('T_PROVEIDOR_FORMA_PAGAMENT')) define('T_PROVEIDOR_FORMA_PAGAMENT','forma de pagament');
if(!defined('T_PROVEIDOR_DIA_1_PAGAMENT')) define('T_PROVEIDOR_DIA_1_PAGAMENT','dia 1 pagament');
if(!defined('T_PROVEIDOR_DIA_2_PAGAMENT')) define('T_PROVEIDOR_DIA_2_PAGAMENT','dia 2 pagament');
if(!defined('T_PROVEIDOR_COMPTE_BANCARI')) define('T_PROVEIDOR_COMPTE_BANCARI','compte bancari');
if(!defined('T_PROVEIDOR_AFEGEIX_FORMA_PAGAMENT')) define('T_PROVEIDOR_AFEGEIX_FORMA_PAGAMENT','afegir forma de pagament');
if(!defined('T_PROVEIDOR_ELIMINA')) define('T_PROVEIDOR_ELIMINA','elimina');
if(!defined('T_PROVEIDOR_NOM')) define('T_PROVEIDOR_NOM','nom proveidor');
if(!defined('T_PROVEIDOR_NOU')) define('T_PROVEIDOR_NOU','nou proveidor');
if(!defined('T_PROVEIDOR_FITXA')) define('T_PROVEIDOR_FITXA','fitxa proveidor');
if(!defined('T_PROVEIDOR_CIF')) define('T_PROVEIDOR_CIF','CIF proveidor');