<?php
if(!defined('T_PROVEIDOR')) define('T_PROVEIDOR','proveidor');
if(!defined('T_PROVEIDORS')) define('T_PROVEIDORS','proveidors');
if(!defined('T_PROVEIDOR_PREUS')) define('T_PROVEIDOR_PREUS','preus proveidor');
if(!defined('T_PROVEIDOR_DADES_FISCALS')) define('T_PROVEIDOR_DADES_FISCALS','dades fiscals proveidor');
if(!defined('T_PROVEIDOR_ERROR_ESBORRAR_COMANDA')) define('T_PROVEIDOR_ERROR_ESBORRAR_COMANDA','El proveidor no es pot eliminar, té comandes assignades');
if(!defined('T_PROVEIDOR_ERROR_ESBORRAR_ALBARA')) define('T_PROVEIDOR_ERROR_ESBORRAR_ALBARA','El proveidor no es pot eliminar, té albarans assignats');
if(!defined('T_PROVEIDOR_ERROR_ESBORRAR_FACTURA')) define('T_PROVEIDOR_ERROR_ESBORRAR_FACTURA','El proveidor no es pot eliminar, té factures assignades');
if(!defined('T_PROVEIDOR_DADES_FACTURACIO')) define('T_PROVEIDOR_DADES_FACTURACIO','dades facturació');
if(!defined('T_PROVEIDOR_COMPTE_COMPTABLE')) define('T_PROVEIDOR_COMPTE_COMPTABLE','compte comptable');
if(!defined('T_PROVEIDOR_FORMA_PAGAMENT')) define('T_PROVEIDOR_FORMA_PAGAMENT','forma de pagament');
if(!defined('T_PROVEIDOR_DIA_1_PAGAMENT')) define('T_PROVEIDOR_DIA_1_PAGAMENT','dia 1 pagament');
if(!defined('T_PROVEIDOR_DIA_2_PAGAMENT')) define('T_PROVEIDOR_DIA_2_PAGAMENT','dia 2 pagament');
if(!defined('T_PROVEIDOR_COMPTE_BANCARI')) define('T_PROVEIDOR_COMPTE_BANCARI','compte bancari');
if(!defined('T_PROVEIDOR_AFEGEIX_FORMA_PAGAMENT')) define('T_PROVEIDOR_AFEGEIX_FORMA_PAGAMENT','afegir forma de pagament');
if(!defined('T_PROVEIDOR_ELIMINA')) define('T_PROVEIDOR_ELIMINA','elimina');
if(!defined('T_PROVEIDOR_NOM')) define('T_PROVEIDOR_NOM','nom proveidor');
if(!defined('T_PROVEIDOR_NOU')) define('T_PROVEIDOR_NOU','nou proveidor');
if(!defined('T_PROVEIDOR_FITXA')) define('T_PROVEIDOR_FITXA','fitxa proveidor');
if(!defined('T_PROVEIDOR_CIF')) define('T_PROVEIDOR_CIF','CIF proveidor');

/* CONG CA */

if(!defined('T_ERROR_FALTEN_CAMPS')) define('T_ERROR_FALTEN_CAMPS','Falten camps o algun camp es incorrecte');
if(!defined('T_ERROR_CAMPS_NO_EXIXTEIX')) define('T_ERROR_CAMPS_NO_EXIXTEIX','El camp no existeix');
if(!defined('T_PERMIS_DENEGAT')) define('T_PERMIS_DENEGAT','Permís denegat');
if(!defined('T_SI')) define('T_SI','si');
if(!defined('T_NO')) define('T_NO','no');
if(!defined('T_PERMIS')) define('T_PERMIS','permís');
if(!defined('T_CAMP_OBLIGATORI')) define('T_CAMP_OBLIGATORI','aquest camp és obligatori');
if(!defined('T_NO_SHA_POGUT')) define('T_NO_SHA_POGUT','no s\'ha pogut');
if(!defined('T_CAMP')) define('T_CAMP','camp');
if(!defined('T_CANCELAR')) define('T_CANCELAR','cancel·lar');
if(!defined('T_AFEGIR')) define('T_AFEGIR','afegir');
if(!defined('T_MODIFICAR')) define('T_MODIFICAR','modificar');
if(!defined('T_ENVIAR')) define('T_ENVIAR','enviar');
if(!defined('T_ENVIAT')) define('T_ENVIAT','enviat');
if(!defined('T_ELIMINA')) define('T_ELIMINA','elimina');
if(!defined('T_ELIMINAR')) define('T_ELIMINAR','eliminar');
if(!defined('T_INICIAR_SESSION')) define('T_INICIAR_SESSION','iniciar sessió');
if(!defined('T_CONTRASENYA')) define('T_CONTRASENYA','contrasenya');
if(!defined('T_CODI_VALIDACIO')) define('T_CODI_VALIDACIO','codi de validació');
if(!defined('T_FORCAR')) define('T_FORCAR','forçar');
if(!defined('T_DADESPERSONALS')) define('T_DADESPERSONALS','dades personals');
if(!defined('T_DADES')) define('T_DADES','dades');
if(!defined('T_DADES_ACCES')) define('T_DADES_ACCES','dades d\'accés');
if(!defined('T_ULTIM_ACCES')) define('T_ULTIM_ACCES','últim accés');
if(!defined('T_GUARDAR')) define('T_GUARDAR','Guardar');
if(!defined('T_NO_TENS_PERMISOS')) define('T_NO_TENS_PERMISOS','No tens permisos');
if(!defined('T_SEGUENT')) define('T_SEGUENT','següent');
if(!defined('T_ANTERIOR')) define('T_ANTERIOR','anterior');
if(!defined('T_FITXA')) define('T_FITXA','fitxa');
if(!defined('T_TITOL')) define('T_TITOL','títol');
if(!defined('T_ALIAS')) define('T_ALIAS','Alias');
if(!defined('T_COMENTARIS')) define('T_COMENTARIS','comentaris');
if(!defined('T_VALOR')) define('T_VALOR','valor');
if(!defined('T_SEGUR_QUE_VOLS_ESBORRAR')) define('T_SEGUR_QUE_VOLS_ESBORRAR','segur que vols esborrar?');
if(!defined('T_AQUEST')) define('T_AQUEST','aquest');
if(!defined('T_AQUESTA')) define('T_AQUESTA','aquesta');
if(!defined('T_GESTIO')) define('T_GESTIO','Gestió');
if(!defined('T_EDIT')) define('T_EDIT','edit');
if(!defined('T_EDITA')) define('T_EDITA','edita');
if(!defined('T_VALIDAT')) define('T_VALIDAT','validat');
if(!defined('T_NOM')) define('T_NOM','nom');
if(!defined('T_COGNOM')) define('T_COGNOM','cognom');
if(!defined('T_COGNOMS')) define('T_COGNOMS','cognoms');
if(!defined('T_COLOR')) define('T_COLOR','color');
if(!defined('T_NOU')) define('T_NOU','nou');
if(!defined('T_NOVA')) define('T_NOVA','nova');
if(!defined('T_TOTS')) define('T_TOTS','tots');
if(!defined('T_TOTES')) define('T_TOTES','totes');
if(!defined('T_TOT')) define('T_TOT','tot');
if(!defined('T_LOGIN')) define('T_LOGIN','login');
if(!defined('T_EMAIL')) define('T_EMAIL','correu electrònic');
if(!defined('T_CANVIAR')) define('T_CANVIAR','canviar');
if(!defined('T_ACTIU')) define('T_ACTIU','actiu');
if(!defined('T_ACTIUS')) define('T_ACTIUS','actius');
if(!defined('T_FILTRE_MULTIPLE')) define('T_FILTRE_MULTIPLE','multiple');
if(!defined('T_CERCA')) define('T_CERCA','cerca');
if(!defined('T_CONFIRMAR')) define('T_CONFIRMAR','confirmar');
if(!defined('T_AVUI')) define('T_AVUI','avui');
if(!defined('T_VEURE_MES')) define('T_VEURE_MES','veure més');
if(!defined('T_ESTAT')) define('T_ESTAT','estat');
if(!defined('T_LLISTAT')) define('T_LLISTAT','llistat');
if(!defined('T_DATA')) define('T_DATA','data');
if(!defined('T_PREU')) define('T_PREU','preu');
if(!defined('T_TOTAL')) define('T_TOTAL','total');
if(!defined('T_PENDENT')) define('T_PENDENT','pendent');
if(!defined('T_FACTURAT')) define('T_FACTURAT','facturat');
if(!defined('T_FACTURACIO')) define('T_FACTURACIO','facturació');
if(!defined('T_TORNAR')) define('T_TORNAR','tornar');
if(!defined('T_DUPLICAR')) define('T_DUPLICAR','duplicar');
if(!defined('T_HAS_OBLIDAT_CONTRASENYA')) define('T_HAS_OBLIDAT_CONTRASENYA','has oblidat la contrasenya?');
if(!defined('T_COPIAT')) define('T_COPIAT','copiat!');

if(!defined('T_QUANTITAT')) define('T_QUANTITAT','quantitat');
if(!defined('T_REFERENCIA')) define('T_REFERENCIA','referència');
if(!defined('T_LOT')) define('T_LOT','lot');
if(!defined('T_CADUCITAT')) define('T_CADUCITAT','caducitat');
if(!defined('T_ESCOLLIR')) define('T_ESCOLLIR','escollir');
if(!defined('T_REBUT')) define('T_REBUT','rebut');
if(!defined('T_CORREU_ELECTRONIC')) define('T_CORREU_ELECTRONIC','correu electronic');
if(!defined('T_CONTACTE')) define('T_CONTACTE','contacte');
if(!defined('T_TELEFON')) define('T_TELEFON','telèfon');
if(!defined('T_FISCALS')) define('T_FISCALS','fiscals');
if(!defined('T_FISCAL')) define('T_FISCAL','fiscal');
if(!defined('T_DIRECCIO')) define('T_DIRECCIO','adreça');
if(!defined('T_CODI')) define('T_CODI','codi');
if(!defined('T_POBLACIO')) define('T_POBLACIO','població');
if(!defined('T_PROVINCIA')) define('T_PROVINCIA','província');
if(!defined('T_PREDETERMINAT')) define('T_PREDETERMINAT','predeterminat');
if(!defined('T_OBSERVACIONS')) define('T_OBSERVACIONS','observacions');
if(!defined('T_REBUDA')) define('T_REBUDA','rebuda');
if(!defined('T_ENVIAMENT')) define('T_ENVIAMENT','enviament');
if(!defined('T_VENCIMENT')) define('T_VENCIMENT','venciment');
if(!defined('T_DESCRIPCIO')) define('T_DESCRIPCIO','descripció');
if(!defined('T_CAIXA')) define('T_CAIXA','caixa');
if(!defined('T_CAIXES')) define('T_CAIXES','caixes');
if(!defined('T_COMANDA')) define('T_COMANDA','comanda');
if(!defined('T_ALBARA')) define('T_ALBARA','albara');
if(!defined('T_ADJUNTEM')) define('T_ADJUNTEM','adjuntem');
if(!defined('T_SENSE')) define('T_SENSE','sense');
if(!defined('T_ORDRE')) define('T_ORDRE','ordre');
if(!defined('T_LLISTAR')) define('T_LLISTAR','llistar');
if(!defined('T_INICI')) define('T_INICI','inici');
if(!defined('T_ENTRADA')) define('T_ENTRADA','entrada');
if(!defined('T_CONFIGURACIO_SISTEMA')) define('T_CONFIGURACIO_SISTEMA','configuració sistema');
if(!defined('T_GRUP')) define('T_GRUP','grup');
if(!defined('T_GRUPS')) define('T_GRUPS','grups');
if(!defined('T_OPERACIO')) define('T_OPERACIO','operacio');
if(!defined('T_OPERACIONS')) define('T_OPERACIONS','operacions');
if(!defined('T_PARAMETRES')) define('T_PARAMETRES','paràmetres');
if(!defined('T_FILTRAT_PER')) define('T_FILTRAT_PER','filtrat per');
if(!defined('T_NUM_COMPTABLE')) define('T_NUM_COMPTABLE','número comptable');
if(!defined('T_ARXIU')) define('T_ARXIU','arxiu');
if(!defined('T_ALEATORIA')) define('T_ALEATORIA','aleatòria');
if(!defined('T_CANVIAR_CONTRASENYA')) define('T_CANVIAR_CONTRASENYA','canviar contrasenya');
if(!defined('T_OBERT')) define('T_OBERT','obert');
if(!defined('T_LIMITAT')) define('T_LIMITAT','limitat');
if(!defined('T_DIA')) define('T_DIA','dia');
if(!defined('T_DIES')) define('T_DIES','dies');
if(!defined('T_OPCIONS')) define('T_OPCIONS','opcions');
if(!defined('T_RESULTAT_BUIT')) define('T_RESULTAT_BUIT','resultat buit');
if(!defined('T_NO_HI_HA_RESULTATS')) define('T_NO_HI_HA_RESULTATS','ni hi ha resultats');
if(!defined('T_CONFIGURACIO_PARAMETRES')) define('T_CONFIGURACIO_PARAMETRES','configuració paràmetres');
if(!defined('T_COMPROVA_PARAMETRES')) define('T_COMPROVA_PARAMETRES','comprova paràmetres');
if(!defined('T_NOM_FISCAL')) define('T_NOM_FISCAL','nom fiscal');
if(!defined('T_DIRECCIO_FACTURACIO')) define('T_DIRECCIO_FACTURACIO','adreça de facturació');
if(!defined('T_CODI_POSTAL_FACTURACIO')) define('T_CODI_POSTAL_FACTURACIO','codi postal facturació');
if(!defined('T_POBLACIO_FACTURACIO')) define('T_POBLACIO_FACTURACIO','població facturació');
if(!defined('T_DADES_CONTACTE')) define('T_DADES_CONTACTE','dades contacte');
if(!defined('T_ESBORRAR_PRODUCTE')) define('T_ESBORRAR_PRODUCTE','Segur que vols esborrar aquest producte?');
if(!defined('T_OPERACIO_NO_ES_POT_DESFER')) define('T_OPERACIO_NO_ES_POT_DESFER','aquesta operació no es pot desfer!');
if(!defined('T_CONFIRMACIO_ELIMINAR')) define('T_CONFIRMACIO_ELIMINAR','Sí, esborra\'l!');
if(!defined('T_GRUPS_USUARIS_SEGUR_ELIMINAR')) define('T_GRUPS_USUARIS_SEGUR_ELIMINAR','Segur que vols esborrar aquest grup?');
if(!defined('T_GRUPS_USUARIS_SEGUR_ELIMINAR_USUARI')) define('T_GRUPS_USUARIS_SEGUR_ELIMINAR_USUARI','Segur que vols esborrar aquest usuari del grup?');
if(!defined('T_BANC')) define('T_BANC','banc');
if(!defined('T_BANCS')) define('T_BANCS','bancs');
if(!defined('T_TANCAR')) define('T_TANCAR','tancar');
if(!defined('T_DIA')) define('T_DIA','dia');
if(!defined('T_HORARI')) define('T_HORARI','horari');
if(!defined('T_RESUM')) define('T_RESUM','resum');
if(!defined('T_SEGONS')) define('T_SEGONS','segons');
if(!defined('T_REFUSAT')) define('T_REFUSAT','refusat');
if(!defined('T_FI')) define('T_FI','fi');
if(!defined('T_ACCES')) define('T_ACCES','acces');
if(!defined('T_HORA')) define('T_HORA','hora');
if(!defined('T_HORES')) define('T_HORES','hores');
if(!defined('T_MINUTS')) define('T_MINUTS','minuts');
if(!defined('T_INFORMACIO')) define('T_INFORMACIO','informació');
if(!defined('T_DIRECTORI')) define('T_DIRECTORI','directori');
if(!defined('T_DIRECTORIS')) define('T_DIRECTORIS','directoris');
if(!defined('T_DOCUMENTS')) define('T_DOCUMENTS','documents');
if(!defined('T_DESCONNECTA')) define('T_DESCONNECTA','desconnecta');
if(!defined('T_MANTENIR_CONNECTAT')) define('T_MANTENIR_CONNECTAT','mantenir connectat');
if(!defined('T_AUTO_TANCAMENT_DEL_SISTEMA')) define('T_AUTO_TANCAMENT_DEL_SISTEMA','auto Tancament del sistema');
if(!defined('T_AUTO_TANCAMENT_DEL_SISTEMA_COMENTARI')) define('T_AUTO_TANCAMENT_DEL_SISTEMA_COMENTARI','si no indiquen el contrari, el sistema es tancá automaticament');
//
if(!defined('T_CONTRASENYA_ANTIGA')) define('T_CONTRASENYA_ANTIGA','contrasenya antiga');
if(!defined('T_CONTRASENYA_NOVA')) define('T_CONTRASENYA_NOVA','nova contrasenya');
if(!defined('T_CONTRASENYA_CANVIAR')) define('T_CONTRASENYA_CANVIAR','canviar contrasenya');
if(!defined('T_CONTRASENYA_CANVIADA_CORRECTAMENT')) define('T_CONTRASENYA_CANVIADA_CORRECTAMENT','La contrasenya s\'ha canviat correctament');
if(!defined('T_CONTRASENYA_ANTIGA_INCORRECTA')) define('T_CONTRASENYA_ANTIGA_INCORRECTA','La contrasenya antiga incorrecta');
if(!defined('T_CONTRASENYA_GENERAR')) define('T_CONTRASENYA_GENERAR','generar contrasenya');
if(!defined('T_CONTRASENYA_FORÇAR')) define('T_CONTRASENYA_FORÇAR','forçar contrasenya');
if(!defined('T_RECUPERACIO_CONTRASENYA')) define('T_RECUPERACIO_CONTRASENYA','recuperació de contrasenya');
if(!defined('T_RECUPERACIO_CONTRASENYA_ENVIAR')) define('T_RECUPERACIO_CONTRASENYA_ENVIAR','enviar correu');
if(!defined('T_RECUPERACIO_CONTRASENYA_GENERAR_ENVIAR')) define('T_RECUPERACIO_CONTRASENYA_GENERAR_ENVIAR','generar i enviar');
if(!defined('T_RECUPERACIO_CONTRASENYA_ENLLAC')) define('T_RECUPERACIO_CONTRASENYA_ENLLAC','generar enllaç');
if(!defined('T_RECUPERACIO_CONTRASENYA_RESET_EMAIL')) define('T_RECUPERACIO_CONTRASENYA_RESET_EMAIL','reset per email');
if(!defined('T_SEGUR_QUE_VOLS_ENVIAR_RESET_CONTRASENYA')) define('T_SEGUR_QUE_VOLS_ENVIAR_RESET_CONTRASENYA','segur que vols enviar el reset per email?');

if(!defined('T_USUARI_CONTRASENYA_NO_SEGURA_NIVELL_0')) define('T_USUARI_CONTRASENYA_NO_SEGURA_NIVELL_0','La contrasenya ha de tenir un mínim de 4 caracters');
if(!defined('T_USUARI_CONTRASENYA_NO_SEGURA_NIVELL_1')) define('T_USUARI_CONTRASENYA_NO_SEGURA_NIVELL_1','La contrasenya ha de tenir un mínim de 8 caracters, números, lletres, majúscules i minúscules.');
if(!defined('T_USUARI_CONTRASENYA_NO_SEGURA_NIVELL_2')) define('T_USUARI_CONTRASENYA_NO_SEGURA_NIVELL_2','La contrasenya ha de tenir un mínim de 12 caracters, números, lletres, majúscules, minúscules i caracters especials.');
if(!defined('T_USUARI_CONTRASENYA_NO_SEGURA')) define('T_USUARI_CONTRASENYA_NO_SEGURA','La contrasenya no compleix les mesures de seguretat');

if(!defined('T_CATRGORIA_USUARIO')) define('T_CATRGORIA_USUARIO','Categoria');

if(!defined('T_UNITATS')) define('T_UNITATS','unitats');
if(!defined('T_FALTEN')) define('T_FALTEN','falten');
if(!defined('T_CODI_BARRES')) define('T_CODI_BARRES','codi de barres');
if(!defined('T_CODI_COMPTABLE')) define('T_CODI_COMPTABLE','codi comptable');
if(!defined('T_VENTA')) define('T_VENTA','venta');
if(!defined('T_PENDENT_ENTREGA')) define('T_PENDENT_ENTREGA','pendent de lliurament'); 
if(!defined('T_EL_CAMP_NO_EXISTEIX')) define('T_EL_CAMP_NO_EXISTEIX','el camp no existeix o és invàlid');
if(!defined('T_BASE')) define('T_BASE','base');
if(!defined('T_PAIS')) define('T_PAIS','país');
if(!defined('T_EXPORTAR')) define('T_EXPORTAR','exportar');
if(!defined('T_TIPUS')) define('T_TIPUS','tipus');
if(!defined('T_NUMERO')) define('T_NUMERO','número');
if(!defined('T_ENTREGADA')) define('T_ENTREGADA','lliurada');
if(!defined('T_ENTREGADA_PARCIAL')) define('T_ENTREGADA_PARCIAL','lliurada parcial');
if(!defined('T_DESTINATARIS_SEPARATS_PER_COMES')) define('T_DESTINATARIS_SEPARATS_PER_COMES','destinataris: (Separats per ,)');
if(!defined('T_ENVIADA')) define('T_ENVIADA','enviada');
if(!defined('T_COBRADA')) define('T_COBRADA','cobrada');
if(!defined('T_PAGADA')) define('T_PAGADA','pagada');
if(!defined('T_CONDICIONS_PAGAMENT')) define('T_CONDICIONS_PAGAMENT','condicions de pagament');
if(!defined('T_PAGINA')) define('T_PAGINA','pàgina');
if(!defined('T_CODI_POSTAL')) define('T_CODI_POSTAL','codi postal');
if(!defined('T_PER')) define('T_PER','per');
if(!defined('T_DIRECCIO_ENTREGA')) define('T_DIRECCIO_ENTREGA','adreça d\'entrega');
if(!defined('T_FACTURA')) define('T_FACTURA','factura');
if(!defined('T_TANCAR_SESSION')) define('T_TANCAR_SESSION','tancar sessió');
if(!defined('T_FALTA_ID')) define('T_FALTA_ID','falta identificador');
if(!defined('T_ERROR_EN_MODIFICAR')) define('T_ERROR_EN_MODIFICAR','error en modificar');
if(!defined('T_QUANTITAT_MIN')) define('T_QUANTITAT_MIN','quantitat minima');
if(!defined('T_REFERENCIA')) define('T_REFERENCIA','referencia');
if(!defined('T_SUBTOTAL')) define('T_SUBTOTAL','subtotal');
if(!defined('T_IVA')) define('T_IVA','IVA');
if(!defined('T_IRPF')) define('T_IRPF','IRPF');
if(!defined('T_DE')) define('T_DE','de');
if(!defined('T_FINS')) define('T_FINS','fins');
if(!defined('T_CARREGANT')) define('T_CARREGANT','carregant');
if(!defined('T_DATA_INICI_ANY')) define('T_DATA_INICI_ANY','data inici any');
if(!defined('T_DATA_FI_ANY')) define('T_DATA_FI_ANY','data fi any');
if(!defined('T_ANY')) define('T_ANY','any');
if(!defined('T_IDIOMA')) define('T_IDIOMA','idioma');
if(!defined('T_COMPTABILITAT')) define('T_COMPTABILITAT','comptabilitat');
if(!defined('T_DESCARREGAR')) define('T_DESCARREGAR','descarregar');
if(!defined('T_IMPORTAR_ARCHIVO')) define('T_IMPORTAR_ARCHIVO','Importar fitxer');
if(!defined('T_MAX_MIDA_ARCHIVO')) define('T_MAX_MIDA_ARCHIVO','Màx mida');
if(!defined('T_PAGINA_INICI')) define('T_PAGINA_INICI','pàgina d\'inici');
if(!defined('T_SI')) define('T_SI','sí');
if(!defined('T_FOTOGRAFIA')) define('T_FOTOGRAFIA','fotografia');
if(!defined('T_LOGO_IMPORTAR')) define('T_LOGO_IMPORTAR','importar logo...');
if(!defined('T_SEGUR_QUE_VOLS_ESBORRAR_LOGO')) define('T_SEGUR_QUE_VOLS_ESBORRAR_LOGO','segur que vols esborrar aquest logo?');
if(!defined('T_IMATGE_PAGINA_INICI_AFEGEIX')) define('T_IMATGE_PAGINA_INICI_AFEGEIX','afegeix logo a la pàgina d\'inici');
if(!defined('T_SUPORT')) define('T_SUPORT','Suport');
if(!defined('T_SUPORT_ONLINE')) define('T_SUPORT_ONLINE','Suport online');
if(!defined('T_BUIDAR')) define('T_BUIDAR','buidar');

// Operacions
if(!defined('T_OPERACIONS_ETIQUETES_GRUP')) define('T_OPERACIONS_ETIQUETES_GRUP','grup d\'etiquetes');
if(!defined('T_ETIQUETA_SEGUR_ESBORRAR_GRUP')) define('T_ETIQUETA_SEGUR_ESBORRAR_GRUP','Segur que vols esborrar aquest grup d\'etiquetes?');
if(!defined('T_OPERACIONS_ETIQUETA')) define('T_OPERACIONS_ETIQUETA','etiqueta');
if(!defined('T_OPERACIONS_NOVA')) define('T_OPERACIONS_NOVA','nova operació');

/**
 * error Autenticació
 */
if(!defined('T_JSON_ERRORS_AUTENTICACIO')) define('T_JSON_ERRORS_AUTENTICACIO','{"0":"Usuari i contrasenya no vàlids","2":"Contrasenya no ès vàlida","3":"Sessió caducada","4":"Accés denegat","5":"Codi incorrecte","-1":"IP no autoritzada","-2":"Horari no autoritzat","-10":"Error no classificat"}');
if(!defined('T_INTRUDUEIX_LES_TEVES_DADES')) define('T_INTRUDUEIX_LES_TEVES_DADES','Introdueix les teves dades per accedir');
if(!defined('T_INTRUDUEIX_BENVINGUT_DE_NOU')) define('T_INTRUDUEIX_BENVINGUT_DE_NOU','Benvingut de nou');
if(!defined('T_NO_HI_HA_CAMP')) define('T_NO_HI_HA_CAMP','no hi ha el camp');
/**
 * DIES
 */
if(!defined('T_DILLUNS')) define('T_DILLUNS','dilluns');
if(!defined('T_DIMARTS')) define('T_DIMARTS','dimarts');
if(!defined('T_DIMECRES')) define('T_DIMECRES','dimecres');
if(!defined('T_DIJOUS')) define('T_DIJOUS','dijous');
if(!defined('T_DIVENDRES')) define('T_DIVENDRES','divendres');
if(!defined('T_DISSABTE')) define('T_DISSABTE','dissabte');
if(!defined('T_DIUMENGE')) define('T_DIUMENGE','diumenge');
if(!defined('T_INDEFINIT')) define('T_INDEFINIT','indefinit');

/**
 * MESOS
 */
if(!defined('T_MESOS')) define('T_MESOS', ' [ { "idMes": 1, "nomMes": "Gener" }, { "idMes": 2, "nomMes": "Febrer" }, { "idMes": 3, "nomMes": "Març" }, { "idMes": 4, "nomMes": "Abril" }, { "idMes": 5, "nomMes": "Maig" }, { "idMes": 6, "nomMes": "Juny" }, { "idMes": 7, "nomMes": "Juliol" }, { "idMes": 8, "nomMes": "Agost" }, { "idMes": 9, "nomMes": "Setembre" }, { "idMes": 10, "nomMes": "Octubre" }, { "idMes": 11, "nomMes": "Novembre" }, { "idMes": 12, "nomMes": "Desembre" } ]');